---
# chezmoi:template:left-delimiter="# {{"
# {{ $version := "3.4.0" -}}
# {{ $url := printf "%s%s" "https://github.com/ryanoasis/nerd-fonts/releases/download/v" $version -}}

HackNerdFont-Regular.ttf:
  type: archive-file
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v# {{ $version }}/Hack.zip
  path: HackNerdFont-Regular.ttf
  refreshPeriod: "# {{ .externalRefreshPeriod }}"

DroidSansMNerdFont-Regular.otf:
  type: archive-file
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v# {{ $version }}/DroidSansMono.zip
  path: DroidSansMNerdFont-Regular.otf

FiraCodeNerdFont-Regular:
  type: "archive"
  url: "# {{ $url -}}/FiraCode.zip"
  refreshPeriod: "# {{ .externalRefreshPeriod }}"
  exact: true
  include: ["FiraCodeNerdFont-*.ttf"]

JetBrainsMonoNerdFont-Regular.ttf:
  type: archive-file
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v# {{ $version }}/JetBrainsMono.zip
  path: JetBrainsMonoNerdFont-Regular.ttf
