---
externalRefreshPeriod: "168h"
packages:
  common:
    - gnupg
    - openssh
    - git
    - git-delta
    - which
    - vim
    - neovim
    - bash
    - bash-completion
    - less
    - bat
    - eza
  arch:
    - keepassxc
    - pkgfile
    - firefox
    - plymouth
    - qbittorrent
  yay:
    - brave-bin
  termux:
  - mandoc
  - oh-my-posh
  - lua-language-server
  - stylua
